services:
  - type: web
    name: bot-vendas
    env: python
    region: oregon
    runtime: python311
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        value: "postgresql://xixa00marketingoff_user:dVejVbGNqXI2EyafJXlYv4eMovSiWsuT@dpg-d98ovvreo5us73fgjuig-a.oregon-postgres.render.com/xixa00marketingoff"
      - key: MP_ACCESS_TOKEN
        sync: false
      - key: MP_PUBLIC_KEY
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: VALOR_MINIMO_PIX
        value: "10.00"
      - key: VALOR_MAXIMO_PIX
        value: "500.00"
      - key: TEMPO_EXPIRACAO_PIX
        value: "300"
      - key: BONUS_DEPOSITO_PORCENTAGEM
        value: "5.0"
      - key: COMISSAO_AFILIADO_PADRAO
        value: "10.0"
      - key: GRUPO_SUPORTE_LINK
        value: "https://t.me/seu_grupo"
      - key: TERMOS_USO_LINK
        value: "https://telegra.ph/Termos"
      - key: LOG_LEVEL
        value: "INFO"
